-- 仪器原始记录主表
-- 说明：保存原始记录生成行为、模板快照、仪器信息及平台操作上下文。
-- 执行顺序：先执行本文件，再执行 dcb_tbs_instorigd.sql。

create table DCB_TBS_INSTORIGM
(
  FORIGSEQ         NUMBER generated by default as identity,
  FORIGGUID        VARCHAR2(64) default rawtohex(sys_guid()) not null,
  FORIGNO          VARCHAR2(80) not null,
  FORIGNM          VARCHAR2(200) not null,
  FRECORDSTATUS    VARCHAR2(20) default 'GENERATED' not null,
  FGENERATEMODE    VARCHAR2(20) not null,
  FTEMPLSEQ        VARCHAR2(64) not null,
  FTEMPLNM         VARCHAR2(200) not null,
  FTEMPLVER        VARCHAR2(50),
  FTEMPLSNAPSHOT   CLOB not null,
  FINSTNO          VARCHAR2(80) not null,
  FINSTNM          VARCHAR2(200) not null,
  FDPTNO           VARCHAR2(50),
  FDPTNM           VARCHAR2(200),
  FDATABEGINDT     DATE,
  FDATAENDDT       DATE,
  FSAMPLECOUNT     NUMBER(10) default 0 not null,
  FITEMCOUNT       NUMBER(10) default 0 not null,
  FDATACOUNT       NUMBER(10) default 0 not null,
  FSOURCEFILECOUNT NUMBER(10) default 0 not null,
  FSOURCEHASH      VARCHAR2(64),
  FRESULTDISEQ     NUMBER(20),
  FSNAPSHOTVER     VARCHAR2(20) default 'V1' not null,
  FREMARK          VARCHAR2(1000),
  FCREATEDT        DATE default sysdate not null,
  FCREATEEMPID     VARCHAR2(50) not null,
  FCREATEEMPNM     VARCHAR2(50) not null,
  FINVALIDDT       DATE,
  FINVALIDEMPID    VARCHAR2(50),
  FINVALIDEMPNM    VARCHAR2(50),
  FINVALIDREASON   VARCHAR2(1000),
  FOPDT            DATE default sysdate not null,
  FOPEMPID         VARCHAR2(50) not null,
  FOPEMPNM         VARCHAR2(50) not null,
  FDATAHIINO       NUMBER(20) not null,
  FSRVHIINO        NUMBER(20) not null,
  FIFVALID         VARCHAR2(10) default '是' not null,
  constraint PK_DCB_TBS_INSTORIGM primary key (FORIGSEQ),
  constraint UK_DCB_INSTORIGM_GUID unique (FORIGGUID),
  constraint UK_DCB_INSTORIGM_NO unique (FDATAHIINO, FORIGNO),
  constraint CK_DCB_INSTORIGM_STATUS check (FRECORDSTATUS in ('GENERATED', 'VOID')),
  constraint CK_DCB_INSTORIGM_MODE check (FGENERATEMODE in ('FILE', 'SAMPLE', 'ITEM')),
  constraint CK_DCB_INSTORIGM_VALID check (FIFVALID in ('是', '否')),
  constraint CK_DCB_INSTORIGM_COUNT check
    (FSAMPLECOUNT >= 0 and FITEMCOUNT >= 0 and FDATACOUNT >= 0 and FSOURCEFILECOUNT >= 0)
);

comment on table DCB_TBS_INSTORIGM is '仪器原始记录主表';
comment on column DCB_TBS_INSTORIGM.FORIGSEQ is '原始记录本地序号，自增主键';
comment on column DCB_TBS_INSTORIGM.FORIGGUID is '原始记录全局唯一标识';
comment on column DCB_TBS_INSTORIGM.FORIGNO is '原始记录编号';
comment on column DCB_TBS_INSTORIGM.FORIGNM is '原始记录名称';
comment on column DCB_TBS_INSTORIGM.FRECORDSTATUS is '业务状态：GENERATED已生成、VOID已作废';
comment on column DCB_TBS_INSTORIGM.FGENERATEMODE is '生成组织模式：FILE来源文件模式、SAMPLE样品模式、ITEM项目模式';
comment on column DCB_TBS_INSTORIGM.FTEMPLSEQ is '原始记录模板标识';
comment on column DCB_TBS_INSTORIGM.FTEMPLNM is '生成时模板名称快照';
comment on column DCB_TBS_INSTORIGM.FTEMPLVER is '生成时模板版本';
comment on column DCB_TBS_INSTORIGM.FTEMPLSNAPSHOT is '模板结构快照，含页眉、说明、列映射、签字、页脚和格式规则';
comment on column DCB_TBS_INSTORIGM.FINSTNO is '仪器接口编号';
comment on column DCB_TBS_INSTORIGM.FINSTNM is '生成时仪器名称快照';
comment on column DCB_TBS_INSTORIGM.FDPTNO is '生成部门编号';
comment on column DCB_TBS_INSTORIGM.FDPTNM is '生成部门名称';
comment on column DCB_TBS_INSTORIGM.FDATABEGINDT is '纳入记录的数据起始时间';
comment on column DCB_TBS_INSTORIGM.FDATAENDDT is '纳入记录的数据结束时间';
comment on column DCB_TBS_INSTORIGM.FSAMPLECOUNT is '样品数量';
comment on column DCB_TBS_INSTORIGM.FITEMCOUNT is '检测项目数量';
comment on column DCB_TBS_INSTORIGM.FDATACOUNT is '快照数据行数';
comment on column DCB_TBS_INSTORIGM.FSOURCEFILECOUNT is '来源采集文件数量';
comment on column DCB_TBS_INSTORIGM.FSOURCEHASH is '本次选取源数据摘要，用于重复生成识别';
comment on column DCB_TBS_INSTORIGM.FRESULTDISEQ is '最终生成文件在HII.IB_TBS_DETAILEDINF中的FDISEQ';
comment on column DCB_TBS_INSTORIGM.FSNAPSHOTVER is '快照结构版本';
comment on column DCB_TBS_INSTORIGM.FREMARK is '备注';
comment on column DCB_TBS_INSTORIGM.FCREATEDT is '首次生成时间';
comment on column DCB_TBS_INSTORIGM.FCREATEEMPID is '创建人账号';
comment on column DCB_TBS_INSTORIGM.FCREATEEMPNM is '创建人姓名';
comment on column DCB_TBS_INSTORIGM.FINVALIDDT is '作废时间';
comment on column DCB_TBS_INSTORIGM.FINVALIDEMPID is '作废人账号';
comment on column DCB_TBS_INSTORIGM.FINVALIDEMPNM is '作废人姓名';
comment on column DCB_TBS_INSTORIGM.FINVALIDREASON is '作废原因';
comment on column DCB_TBS_INSTORIGM.FOPDT is '最后操作时间';
comment on column DCB_TBS_INSTORIGM.FOPEMPID is '最后操作人账号';
comment on column DCB_TBS_INSTORIGM.FOPEMPNM is '最后操作人姓名';
comment on column DCB_TBS_INSTORIGM.FDATAHIINO is '数据所属机构编号';
comment on column DCB_TBS_INSTORIGM.FSRVHIINO is '系统所属机构编号，对应ILCFG.FHIINO';
comment on column DCB_TBS_INSTORIGM.FIFVALID is '有效标志：是、否';

create index IX_DCB_INSTORIGM_QUERY
  on DCB_TBS_INSTORIGM (FDATAHIINO, FIFVALID, FCREATEDT);

create index IX_DCB_INSTORIGM_INST
  on DCB_TBS_INSTORIGM (FDATAHIINO, FINSTNO, FCREATEDT);

create index IX_DCB_INSTORIGM_TEMPL
  on DCB_TBS_INSTORIGM (FTEMPLSEQ, FTEMPLVER);

create index IX_DCB_INSTORIGM_STATUS
  on DCB_TBS_INSTORIGM (FDATAHIINO, FRECORDSTATUS, FOPDT);
