-- 仪器原始记录数据快照表
-- 说明：固化生成原始记录时使用的LIS_INSTDATA_NEW解析数据。
-- 快照生成后不随源数据重新解析、修改或删除而变化。

create table DCB_TBS_INSTORIGD
(
  FORIGDSEQ          NUMBER generated by default as identity,
  FORIGGUID          VARCHAR2(64) not null,
  FROWSEQ            NUMBER(10) not null,
  FSOURCEFGUID       VARCHAR2(64) not null,
  FSOURCEFDISEQ      NUMBER(20),
  FSOURCEINSTNO      VARCHAR2(80) not null,
  FSOURCESAMPSEQ     NUMBER(20),
  FSOURCESAMPNO      VARCHAR2(100),
  FSOURCEITEMSEQ     VARCHAR2(100),
  FSOURCEEMPID       VARCHAR2(50),
  FSOURCEOPDT        DATE,
  FSAMPNO            VARCHAR2(100),
  FSAMPNM            VARCHAR2(200),
  FSAMPCATEGORYNO    VARCHAR2(50),
  FSAMPCATEGORYNM    VARCHAR2(200),
  FITEMSEQ           VARCHAR2(100),
  FITEMNM            VARCHAR2(200),
  FRSLT              VARCHAR2(500),
  FRSLT1             VARCHAR2(500),
  FRSLT2             VARCHAR2(500),
  FRSLT3             VARCHAR2(500),
  FRSLT4             VARCHAR2(500),
  FRSLT5             VARCHAR2(500),
  FRSLT6             VARCHAR2(500),
  FRSLTDESC          VARCHAR2(2000),
  FMW                VARCHAR2(100),
  FRESULTUNIT        VARCHAR2(100),
  FFILENM            VARCHAR2(500),
  FCOLLECTDT         DATE,
  FEXTSNAPSHOT       CLOB,
  FOPDT              DATE default sysdate not null,
  FOPEMPID           VARCHAR2(50) not null,
  FOPEMPNM           VARCHAR2(50) not null,
  FDATAHIINO         NUMBER(20) not null,
  FSRVHIINO          NUMBER(20) not null,
  FIFVALID           VARCHAR2(10) default '是' not null,
  constraint PK_DCB_TBS_INSTORIGD primary key (FORIGDSEQ),
  constraint UK_DCB_INSTORIGD_ROW unique (FORIGGUID, FROWSEQ),
  constraint UK_DCB_INSTORIGD_SRC unique (FORIGGUID, FSOURCEFGUID),
  constraint FK_DCB_INSTORIGD_MAIN foreign key (FORIGGUID)
    references DCB_TBS_INSTORIGM (FORIGGUID),
  constraint CK_DCB_INSTORIGD_ROW check (FROWSEQ > 0),
  constraint CK_DCB_INSTORIGD_VALID check (FIFVALID in ('是', '否'))
);

comment on table DCB_TBS_INSTORIGD is '仪器原始记录数据快照表';
comment on column DCB_TBS_INSTORIGD.FORIGDSEQ is '快照明细本地序号，自增主键';
comment on column DCB_TBS_INSTORIGD.FORIGGUID is '所属原始记录全局唯一标识';
comment on column DCB_TBS_INSTORIGD.FROWSEQ is '原始记录内显示顺序';
comment on column DCB_TBS_INSTORIGD.FSOURCEFGUID is '来源LIS_INSTDATA_NEW.FGUID';
comment on column DCB_TBS_INSTORIGD.FSOURCEFDISEQ is '来源采集文件FDISEQ';
comment on column DCB_TBS_INSTORIGD.FSOURCEINSTNO is '来源仪器接口编号';
comment on column DCB_TBS_INSTORIGD.FSOURCESAMPSEQ is '来源样品序号，允许为0或空';
comment on column DCB_TBS_INSTORIGD.FSOURCESAMPNO is '来源样品编号';
comment on column DCB_TBS_INSTORIGD.FSOURCEITEMSEQ is '来源检测项目编号';
comment on column DCB_TBS_INSTORIGD.FSOURCEEMPID is '来源解析数据操作人';
comment on column DCB_TBS_INSTORIGD.FSOURCEOPDT is '来源解析数据入库时间';
comment on column DCB_TBS_INSTORIGD.FSAMPNO is '生成时样品编号快照';
comment on column DCB_TBS_INSTORIGD.FSAMPNM is '生成时样品名称快照';
comment on column DCB_TBS_INSTORIGD.FSAMPCATEGORYNO is '生成时样品类别编号';
comment on column DCB_TBS_INSTORIGD.FSAMPCATEGORYNM is '生成时样品类别名称';
comment on column DCB_TBS_INSTORIGD.FITEMSEQ is '生成时检测项目编号快照';
comment on column DCB_TBS_INSTORIGD.FITEMNM is '生成时检测项目名称快照';
comment on column DCB_TBS_INSTORIGD.FRSLT is '来源解析结果原值';
comment on column DCB_TBS_INSTORIGD.FRSLT1 is '来源扩展结果1原值';
comment on column DCB_TBS_INSTORIGD.FRSLT2 is '来源扩展结果2原值';
comment on column DCB_TBS_INSTORIGD.FRSLT3 is '来源扩展结果3原值';
comment on column DCB_TBS_INSTORIGD.FRSLT4 is '来源扩展结果4原值';
comment on column DCB_TBS_INSTORIGD.FRSLT5 is '来源扩展结果5原值';
comment on column DCB_TBS_INSTORIGD.FRSLT6 is '来源扩展结果6原值';
comment on column DCB_TBS_INSTORIGD.FRSLTDESC is '来源结果描述';
comment on column DCB_TBS_INSTORIGD.FMW is '来源单位或分子量字段原值';
comment on column DCB_TBS_INSTORIGD.FRESULTUNIT is '生成时确定的显示单位';
comment on column DCB_TBS_INSTORIGD.FFILENM is '来源采集文件名称快照';
comment on column DCB_TBS_INSTORIGD.FCOLLECTDT is '来源文件采集时间';
comment on column DCB_TBS_INSTORIGD.FEXTSNAPSHOT is '其他仪器扩展字段结构化快照';
comment on column DCB_TBS_INSTORIGD.FOPDT is '最后操作时间';
comment on column DCB_TBS_INSTORIGD.FOPEMPID is '最后操作人账号';
comment on column DCB_TBS_INSTORIGD.FOPEMPNM is '最后操作人姓名';
comment on column DCB_TBS_INSTORIGD.FDATAHIINO is '数据所属机构编号';
comment on column DCB_TBS_INSTORIGD.FSRVHIINO is '系统所属机构编号，对应ILCFG.FHIINO';
comment on column DCB_TBS_INSTORIGD.FIFVALID is '有效标志：是、否';

create index IX_DCB_INSTORIGD_FGUID
  on DCB_TBS_INSTORIGD (FSOURCEFGUID);

create index IX_DCB_INSTORIGD_FDISEQ
  on DCB_TBS_INSTORIGD (FSOURCEFDISEQ);

create index IX_DCB_INSTORIGD_SAMPLE
  on DCB_TBS_INSTORIGD (FSOURCESAMPNO);

create index IX_DCB_INSTORIGD_ITEM
  on DCB_TBS_INSTORIGD (FSOURCEITEMSEQ);

create index IX_DCB_INSTORIGD_QUERY
  on DCB_TBS_INSTORIGD (FDATAHIINO, FORIGGUID, FIFVALID);

