-- 6个 Java 文件与数据库对象的一致性校验（只读）

-- 1. 五张表是否存在。
select OWNER,TABLE_NAME from ALL_TABLES
 where OWNER='HTLIS' and TABLE_NAME in
 ('LIS_CLIENT_INFO','LIS_HEARTBEAT_LOG','LIS_ACQUISITION_LOG',
  'LIS_CLIENT_POLICY','LIS_CLIENT_POLICY_LOG')
 order by TABLE_NAME;

-- 2. 公共字段是否在五张表中完整存在且类型正确。
select TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,DATA_PRECISION,NULLABLE
  from ALL_TAB_COLUMNS
 where OWNER='HTLIS'
   and TABLE_NAME in ('LIS_CLIENT_INFO','LIS_HEARTBEAT_LOG','LIS_ACQUISITION_LOG',
                      'LIS_CLIENT_POLICY','LIS_CLIENT_POLICY_LOG')
   and COLUMN_NAME in ('FGUID','FEMPID','FOPDT','FHIINO')
 order by TABLE_NAME,COLUMN_NAME;

-- 每张表必须得到4个公共字段。
select TABLE_NAME,count(*) COMMON_COLUMN_COUNT
  from ALL_TAB_COLUMNS
 where OWNER='HTLIS'
   and TABLE_NAME in ('LIS_CLIENT_INFO','LIS_HEARTBEAT_LOG','LIS_ACQUISITION_LOG',
                      'LIS_CLIENT_POLICY','LIS_CLIENT_POLICY_LOG')
   and COLUMN_NAME in ('FGUID','FEMPID','FOPDT','FHIINO')
 group by TABLE_NAME
having count(*) <> 4;

-- 3. 两个序列是否存在。
select SEQUENCE_OWNER,SEQUENCE_NAME,LAST_NUMBER,CACHE_SIZE
  from ALL_SEQUENCES
 where SEQUENCE_OWNER='HTLIS'
   and SEQUENCE_NAME in ('SEQ_HEARTBEAT_LOG','SEQ_ACQ_LOG')
 order by SEQUENCE_NAME;

-- 4. 客户端登记是否具备接口鉴权和可信归属前提。
select CLIENT_ID,INSTNO,FDPTNO,FHIINO,FENABLE,FAUTHKEYID,FAUTHSTATUS,
       CLIENT_VER,LAST_HEARTBEAT,FAPPLIEDVER,FAPPLYSTATUS
  from HTLIS.LIS_CLIENT_INFO
 order by CLIENT_ID;

select CLIENT_ID,INSTNO,FHIINO,FENABLE,FAUTHKEYID,FAUTHSTATUS
  from HTLIS.LIS_CLIENT_INFO
 where INSTNO is null or FHIINO is null or FENABLE <> '是'
    or FAUTHKEYID is null or FAUTHSECRETENC is null or FAUTHSTATUS <> 'ACTIVE';

-- 5. 每个客户端只能存在一条当前策略，且发布策略字段完整。
select CLIENT_ID,count(*) CNT from HTLIS.LIS_CLIENT_POLICY
 group by CLIENT_ID having count(*) > 1;

select CLIENT_ID,INSTNO,CONFIG_VER,POLICY_STATUS,INTERFACE_TYPE,
       FILE_PATH,SCAN_INTERVAL,SERVICE_URL,ALLOWED_EXTENSIONS,HEARTBEAT_INTERVAL
  from HTLIS.LIS_CLIENT_POLICY
 where POLICY_STATUS='PUBLISHED'
   and (lower(INTERFACE_TYPE) <> 'http' or FILE_PATH is null or SCAN_INTERVAL is null
        or SERVICE_URL is null or ALLOWED_EXTENSIONS is null or HEARTBEAT_INTERVAL is null);

-- 6. 业务事件接口幂等键是否已有重复数据。
select CLIENT_ID,REQUEST_GUID,count(*) CNT from HTLIS.LIS_ACQUISITION_LOG
 group by CLIENT_ID,REQUEST_GUID having count(*) > 1;

-- 7. 策略应用回执日志不应出现同客户端、同版本、同动作的重复行。
select CLIENT_ID,CONFIG_VER,ACTION_TYPE,count(*) CNT
  from HTLIS.LIS_CLIENT_POLICY_LOG
 where ACTION_TYPE in ('APPLY_SUCCESS','APPLY_FAIL')
 group by CLIENT_ID,CONFIG_VER,ACTION_TYPE
having count(*) > 1;

-- 心跳序号会随客户端进程重启从1开始，不能把 CLIENT_ID+HEARTBEAT_SEQ 建成唯一键。
-- 此查询用于观察重启/重试现象，不作为异常判定。
select CLIENT_ID,HEARTBEAT_SEQ,count(*) CNT
  from HTLIS.LIS_HEARTBEAT_LOG
 group by CLIENT_ID,HEARTBEAT_SEQ
having count(*) > 1;
